### PR TITLE
Move talks to k8s & drone

### PR DESCRIPTION
**Pull request by smeruelo**
Once this is merged, talks docker image will be created, pushed to Quay, and deployed to kubernetes by our Drone server.

Please don't merge until a migration plan is discussed.

Note that the deployment to the staging environment will be limited by https://github.com/src-d/talks/issues/79 and https://github.com/src-d/talks/issues/78. Also, since https is forced, production will show a warning until https://github.com/src-d/talks/issues/77 is solved.

### CODE REVIEW

**Review by rporres — APPROVED** [review]

**Comment by rporres** [comment]
I guess we will have to remove the travis integration

**Comment by smeruelo** [comment]
Applied changes to leave this job the very same way that landing & blog ones. 

I have introduced the variable `BASE_URL` even if it's not currently used, so this way it is prepared to make different builds for stg & prod environments. Please @dpordomingo make use of this variable when solving #79

**Review by dpordomingo — APPROVED** [review]

**Review by rporres — APPROVED** [review]

**Comment by smeruelo** [comment]
Added workaround for [the bug](https://github.com/kubernetes/helm/issues/1707) that @dpordomingo found yesterday. Once you approve it here, I'll apply the same fix to blog and landing.

**Comment by rporres** [comment]
nit: depending on how this is going to be merged, maybe it is better to place the reference of the bug in the drone yaml file too, in case commits get squashed, rebased, etc

**Review by rporres — APPROVED** [review]

**Review by dpordomingo — APPROVED** [review]
lgtm

**Review by dpordomingo — APPROVED** [review]

**Comment by smeruelo** [comment]
Cleaned & rebased master. Ready to be merged, @dpordomingo

**Pull request merged**
